packageExtensions:
  is-immutable-type@*:
    dependencies:
      eslint: '^8.36.0'
  '@parcel/types@*':
    dependencies:
      '@parcel/core': '^2.8.3'
  '@parcel/optimizer-image@*':
    dependencies:
      '@parcel/core': '^2.8.3'
